export const SUBMIT_DATE = 'SUBMIT_DATE';
export const GET_APOD = 'GET_APOD';
export const CREATE_BDAY_FAILURE = 'CREATE_BDAY_FAILURE';
export const CREATE_BDAY_SUCCESS = 'CREATE_BDAY_SUCCESS';
export const DATA_RESET = 'DATA_RESET';
